# Generated by Django 3.1.1 on 2020-11-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(null=True)),
                ('categoria', models.IntegerField(blank=True)),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
